[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ferris-says = "0.3.1"
regex = "1.11.1"

[[bin]]
name="day03"
path="Day 03/day03.rs"

[[bin]]
name="day04"
path="Day 04/day04.rs"

[[bin]]
name="day05"
path="Day 05/day05.rs"